# Docker compose for build pipeline

version: '3.8'

services:
  mock-data-recipient:
    container_name: mock-data-recipient-for-testing
    image: mock-data-recipient-for-testing
    hostname: mock-data-recipient
    ports: 
      - "9001:9001"
    build:
      context: .
      dockerfile: Dockerfile.for-testing
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    volumes:
      - "./_temp/mock-data-recipient/tmp:/tmp"      
    healthcheck:
      test: test -f /app/web/_healthcheck_ready || exit 1
      timeout: 5s
      interval: 5s
      retries: 60
    depends_on:
      mssql:
        condition: service_healthy

  mock-data-recipient-unit-tests:
    container_name: mock-data-recipient-unit-tests
    image: mock-data-recipient-unit-tests
    build:
      context: .
      dockerfile: Dockerfile.unit-tests
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    volumes:
      - "./_temp/mock-data-recipient-unit-tests/testresults:/testresults"
    depends_on:
      mssql:
        condition: service_healthy
      mock-data-recipient:
        condition: service_healthy        

  mssql:
    container_name: sql1
    image: 'mcr.microsoft.com/mssql/server:2019-latest'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pa{}w0rd2019
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S . -U sa -P "Pa{}w0rd2019" -Q "SELECT 1" || exit 1 
      timeout: 10s
      interval: 10s
      retries: 20    
